
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'AAC4167E6D020FF1BEFEF30BD37FC13E'
    
_lr_action_items = {'SEARCH':([0,],[3,]),'WORD':([3,],[8,]),'SHOW':([0,],[5,]),'LIST':([0,],[6,]),'ID':([5,],[9,]),'$end':([1,2,4,6,7,8,9,],[-3,0,-1,-4,-2,-6,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'wargs':([0,],[1,]),'stat':([0,],[2,]),'list':([0,],[4,]),'search':([0,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> stat","S'",1,None,None,None),
  ('stat -> list','stat',1,'p_state','tellme.py',76),
  ('stat -> search','stat',1,'p_state','tellme.py',77),
  ('stat -> wargs','stat',1,'p_state','tellme.py',78),
  ('list -> LIST','list',1,'p_list','tellme.py',83),
  ('wargs -> SHOW ID','wargs',2,'p_wargs','tellme.py',91),
  ('search -> SEARCH WORD','search',2,'p_search','tellme.py',106),
]
