
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'EF086BFABE1E04E4AFFFB55D8E7FA092'
    
_lr_action_items = {'MAP':([0,],[10,]),'WORD':([5,7,8,11,12,15,21,22,],[15,16,17,18,19,20,23,24,]),'SHOW':([0,],[11,]),'OF':([18,],[21,]),'IS':([18,],[22,]),'SIT':([0,],[5,]),'LIST':([0,],[4,]),'LEAVE':([0,],[7,]),'FIELD':([0,],[8,]),'DONE':([0,],[9,]),'DATA':([0,],[12,]),'$end':([1,2,3,4,6,9,10,13,14,16,17,19,20,23,24,],[-1,0,-3,-6,-2,-13,-7,-4,-5,-8,-14,-12,-9,-11,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'map':([0,],[1,]),'stat':([0,],[2,]),'wargs':([0,],[3,]),'list':([0,],[6,]),'data':([0,],[13,]),'spec':([0,],[14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> stat","S'",1,None,None,None),
  ('stat -> map','stat',1,'p_state','ptml.py',58),
  ('stat -> list','stat',1,'p_state','ptml.py',59),
  ('stat -> wargs','stat',1,'p_state','ptml.py',60),
  ('stat -> data','stat',1,'p_state','ptml.py',61),
  ('stat -> spec','stat',1,'p_state','ptml.py',62),
  ('list -> LIST','list',1,'p_list','ptml.py',67),
  ('map -> MAP','map',1,'p_map','ptml.py',72),
  ('wargs -> LEAVE WORD','wargs',2,'p_wargs','ptml.py',77),
  ('spec -> SIT WORD WORD','spec',3,'p_spec','ptml.py',82),
  ('spec -> SHOW WORD IS WORD','spec',4,'p_spec','ptml.py',83),
  ('spec -> SHOW WORD OF WORD','spec',4,'p_spec','ptml.py',84),
  ('data -> DATA WORD','data',2,'p_data','ptml.py',89),
  ('data -> DONE','data',1,'p_data','ptml.py',90),
  ('data -> FIELD WORD','data',2,'p_data','ptml.py',91),
]
